### ISSUE TITLE
Enable typescript reference on backend errors

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#2451]
While logging error stack traces we must ensure the trace will have the reference to the typescript instead of the bundled one, as shown below.

**Additional context**
Please use references like the below one looking for the best way to have it enabled.
https://stackoverflow.com/questions/59000552/how-to-print-stack-trace-with-reference-to-typescript-source-in-nest-js

```
TypeError: Cannot read property 'length' of undefined
    at SpecializedStringBuilder.appendWithEndFiller (/opt/app-root/src/dist/apps/queue-consumers/main.js:711:15)
    at SpecializedStringBuilder.appendStringWithFiller (/opt/app-root/src/dist/apps/queue-consumers/main.js:7456:14)
    at IER12FileDetail.getFixedFormat (/opt/app-root/src/dist/apps/queue-consumers/main.js:14115:16)
    at /opt/app-root/src/dist/apps/queue-consumers/main.js:12160:66
    at Array.map (<anonymous>)
    at IER12IntegrationService.uploadContent (/opt/app-root/src/dist/apps/queue-consumers/main.js:12160:47)
    at IER12ProcessingService.uploadIER12Content (/opt/app-root/src/dist/apps/queue-consumers/main.js:14357:48)
    at IER12ProcessingService.processIER12File (/opt/app-root/src/dist/apps/queue-consumers/main.js:14342:52)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read property 'length' of undefined
    at SpecializedStringBuilder.appendWithEndFiller (/opt/app-root/src/dist/apps/queue-consumers/main.js:711:15)
    at SpecializedStringBuilder.appendStringWithFiller (/opt/app-root/src/dist/apps/queue-consumers/main.js:7456:14)
    at IER12FileDetail.getFixedFormat (/opt/app-root/src/dist/apps/queue-consumers/main.js:14115:16)
    at /opt/app-root/src/dist/apps/queue-consumers/main.js:12160:66
    at Array.map (<anonymous>)
```

**Acceptance criteria**
- [x] Check if this has already be done (Signori may have already updated the config)
- [x] Ensure that error stack traces will contain the typescript file reference.
- [x] Review throw errors with inner exceptions to ensure that the stack trace from nested expectations will be added to logs also.

**Comment by andrepestana-aot** [comment]
It is already referencing to the API source code files:
<img width="1180" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXdFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--733c8211e17358ce7a58de1e222f8c1ea105529b/image.png" alt="image.png" />
